# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64b2c7fb90218b5d53d9bc8ee48327fb980a986b85f80397281974c5cb184691ec3f0231472782f3f3aea7815838c5833e165b79e91b0361802a47a4e704b5f2

test:
  secret_key_base: 3c4fbb404d8cc94ff20904640905948a64ccc4727738dfd06beb71a57310b50c4b4936554ce4c3dd1963b7e772c6f535d7489a173446952e7237279e62318eac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
